downstream_dependencies:
  - h1_hesc
  - mycoplasma_pneumoniae
  - rand_wc_model_gen
email_notifications:
  - jonrkarr@gmail.com
static_analyses:
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
